spring:
  name: company-management-local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/fliper_project
    username: root
    password: 626130  # Use an environment variable instead of hardcoding the password

    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: company-management-pool-local
      max-lifetime: 2000000
      connection-timeout: 30000
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  servlet:
    context-path: /company-management
  port: 8088  # Change if this port is already in use

logging:
  file:
    name: logs/virtustrike-management-service.log  
  pattern:
    console: "%d %-5level [%thread] %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: INFO
    org.springframework.web.servlet.resource: DEBUG
    org.hibernate: INFO
    com.amstech.dairy.management.system: INFO
    org.springframework.security: DEBUG
    com.virtustrike.gaming.pvt.software: DEBUG

app: 
  max-file-size: 5000000